### ISSUE TITLE
[Enhancement request] Reduce node version dependency to something more common?

### ISSUE THREAD

**Issue by DethAriel** [d4rkr00t/whybundled#1]
Hello, thx for the tool!

Is there any chance the node dependency could be downgraded?

**Comment by d4rkr00t** [comment]
What minimum node version would you prefer?

**Comment by DethAriel** [comment]
Node 6 would be great, since it's the [most widely used version of Node](https://nodesource.com/node-by-numbers)

**Comment by d4rkr00t** [comment]
I'll do that

**Comment by d4rkr00t** [comment]
Released as https://github.com/d4rkr00t/whybundled/releases/tag/v1.0.1
