### ISSUE TITLE
How about a "why did not bundle"?

### ISSUE THREAD

**Issue by quetzalsly** [d4rkr00t/whybundled#20]
It would be great to have the program scan my src folder and tell me which files are not being included into the webpack build, in case I missed an import somewhere?

**Comment by d4rkr00t** [comment]
Hey, thanks for reaching out.

Even though I'd really want something like that to exist, I don't think it's in the scope of this tool. 
Also it's quite tricky to do that as there are many ways to implicitly import something in webpack whether it's by using aliases, loaders, etc...
