### ISSUE TITLE
Octal literals are not allowed in strict mode.

### ISSUE THREAD

**Issue by re-gor** [d4rkr00t/whybundled#25]
Hi! First of all, thanks for the nice tool. 

We use flow (version 0.84.0) in our project. I tried to include whybundled in devDependencies and met next issue:

```
> flow --show-all-branches --max-warnings 0 --color always

Error ┈┈┈┈┈node_modules/whybundled/lib/console/progress-bar.js:19:16

Octal literals are not allowed in strict mode.

     16│ }
     17│
     18│ function selectPrevLine(stdout /*: stream$Writable */) {
     19│   stdout.write("\033[1A");
     20│ }
     21│
     22│ module.exports = function createProgressBar(

```

Not the big deal, but it forces to make corrections in .flowconfig

**Comment by d4rkr00t** [comment]
Thanks :) Fixed in https://github.com/d4rkr00t/whybundled/commit/b081525940ff7fccb88f821ca9791e95b3c17f84
