### ISSUE TITLE
Plugins that write on stdout

### ISSUE THREAD

**Issue by GuillaumeCisco** [d4rkr00t/whybundled#5]
Hello there,

I think this is important to note that the `json` file generated as described in the README can contain stdout lines making it nit a json file.

For example, I have some plugins like [SWPrecacheWebpackPlugin](https://github.com/goldhand/sw-precache-webpack-plugin/tree/master/examples), [AutoDllPlugin](https://github.com/asfktz/autodll-webpack-plugin) that write on the stdout outout, so the generated file is not a true json file.

Maybe we should handle the creation of the json file by stripping the written lines at the beginning of the file or find another way to generate a json file correctly.

Right now, we should add a troubleshooting section in the README for warning users about it before they say "it does not work"

**Comment by d4rkr00t** [comment]
Hi :) I'll try to figure something out :)
