### ISSUE TITLE
Overriding `stats` in webpack config

### ISSUE THREAD

**Issue by GuillaumeCisco** [d4rkr00t/whybundled#6]
Hello I had issues for running whybundled because I overrided my `stats` webpack config.

I had:
```javascript
    stats: {
        colors: true,
        reasons: DEBUG,
        hash: DEVELOPMENT,
        version: DEVELOPMENT,
        timings: true,
        chunks: DEVELOPMENT,
        chunkModules: DEVELOPMENT,
        cached: DEVELOPMENT,
        cachedAssets: DEVELOPMENT,
    },
```

And creating the json file with `NODE_ENV=production` disable `reasons`, `chunks` and `chunkedModules`.
I had to comment them like:
```javascript
    stats: {
        colors: true,
        //reasons: DEBUG,
        hash: DEVELOPMENT,
        version: DEVELOPMENT,
        timings: true,
        //chunks: DEVELOPMENT,
        //chunkModules: DEVELOPMENT,
        cached: DEVELOPMENT,
        cachedAssets: DEVELOPMENT,
    },
```

Maybe whybundled can warn us if the generated json files does not contain  `reasons`, `chunks` and `chunkedModules`. Because it needs these objects for working.

**Comment by d4rkr00t** [comment]
Yeah, it definitely should warn. Thanks. I'll add that.

**Comment by GuillaumeCisco** [comment]
Great thanks! :+1:
